language: ruby

rvm:
  - 2.3
  - jruby

env:
  global:
    - JRUBY_OPTS=--dev

sudo: false

before_script:
  - RAILS_ENV=test bundle exec rake --rakefile=test/dummy/Rakefile db:setup

matrix:
  allow_failures:
    - rvm: jruby
